language: php

php: 5.6

env:
  matrix:
    - PHPUNIT_TEST=1
    - PHPCS_TEST=1

before_script:
  - composer install --dev --prefer-dist
  - pyrus install pear/PHP_CodeSniffer
  - phpenv rehash

script:
  - "if [ \"$PHPUNIT_TEST\" = \"1\" ]; then vendor/bin/phpunit tests; fi"
  - "if [ \"$PHPCS_TEST\" = \"1\" ]; then phpcs --standard=PSR2 bin/ src/ tests/; fi"